# Generated by Django 5.0.7 on 2024-10-13 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elsalnet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_type",
            field=models.IntegerField(
                choices=[
                    (0, "Завод"),
                    (1, "Розничная сеть"),
                    (2, "Индивидуальный предприниматель"),
                ],
                default=0,
                editable=False,
                verbose_name="Тип компании",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="выберите компанию-поставщика, если Ваша компания не является заводом",
                limit_choices_to={"level__in": [0, 1]},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="elsalnet.company",
                verbose_name="Компания-поставщик",
            ),
        ),
    ]
